# Build stage
FROM golang:1.22-alpine AS builder

# Set working directory
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o /goatsync ./cmd/goatsync

# Final stage
FROM alpine:latest

# Add non root user
RUN adduser -D -g '' appuser

# Copy binary from builder
COPY --from=builder /goatsync /goatsync

# Use non root user
USER appuser

# Command to run
ENTRYPOINT ["/goatsync"]
